# Dependencies
markdown:         redcarpet
redcarpet:
  extensions: 	  [with_toc_data]

highlighter:         true
#for loop error
excerpt_separator: ""
# Permalinks
permalink:        none
relative_permalinks: false
# Setup
title:            Dineshswamy's hacking log
tagline:          ''
description:      ''
url:              

author:
  name:           'Dinesh swamy'
  url:            

paginate:         false

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/dineshswamy